### ISSUE TITLE
Project not working correctly

### ISSUE THREAD

**Issue by robin271** [JohannesDeml/Unity-Net-Core-Networking-Sockets#3]
Hey started the program on Unity and it worked. However, it never changes when I press send. Do you know what might be the Problem there? It is trying to connect to TCP, but seldomly connects. Adding to that I also cannot rarely press the send button. Any help will be appreciated.

**Comment by JohannesDeml** [comment]
Hello there,
I can't completely follow. What does never change? The text you receive?
Step by Step instructions for TCP:

1. Run WindowsServer/RunTcpServer.bat (and leave it open)
![TCP Commandline Screenshot](https://user-images.githubusercontent.com/4518980/87789671-b39b0f80-c83f-11ea-9b2b-4b0efd111144.png)
2. Open Scenes/NetworkExampleClient.unity and hit play.
3. Click on Connect TCP
![grafik](https://user-images.githubusercontent.com/4518980/87789788-e04f2700-c83f-11ea-89ac-8ad973711555.png)
4. Enter text in the input field and click Send
![grafik](https://user-images.githubusercontent.com/4518980/87790100-55226100-c840-11ea-9998-ed654716becb.png)
5. Enter another text and click Send again
![grafik](https://user-images.githubusercontent.com/4518980/87790172-6c614e80-c840-11ea-991e-e95fa16deae9.png)

You should see the two different message 10 times each (since it is repeating the text 10 times by default).

**Comment by robin271** [comment]
Vielen Dank! Now it seems a lot more understable because of the Server, but I don't know where can I install the Server from?

**Comment by robin271** [comment]
I am sorry for the inconvenience! Everything works fine now! Thank you, for replying so quickly. By the way, can you speak German?

**Comment by robin271** [comment]
Oh and I have one final question: Is there a way to see the Code from the Server side? Would be greatly appreciated since I am trying to understand all of that Server stuff!!

**Comment by JohannesDeml** [comment]
> 
> 
> Oh and I have one final question: Is there a way to see the Code from the Server side? Would be greatly appreciated since I am trying to understand all of that Server stuff!!

Sure, the server code comes from https://github.com/chronoxor/NetCoreServer Take a look at the [performance](https://github.com/chronoxor/NetCoreServer/tree/master/performance) folder. In case of TCP it is just the compiled version of [TcpEchoServer](https://github.com/chronoxor/NetCoreServer/tree/master/performance/TcpEchoServer).




> By the way, can you speak German?

I do speak German, but I would like o stick to English so others can follow the conversation more easily if they have the same question :)

**Comment by robin271** [comment]
Hey I know the following might not fit to the topic perfectly but do you know how do the same server client connection with another wifi? I don't understand at all how I can get another IP adress

**Comment by JohannesDeml** [comment]
Hi again,

well you just need to find out the publicly available ip address of your server. 
* If you get a VPS or set up a server at any online webserver service you will get your own ip, so that is quite straight forward.
* If that server is in the same local network, you need to set to local ip as your target ip (eg. 10.0.0.x or 192.168.0.x)
* If your server is in a different wifi than yours you need to somehow expose that IP to be reachable from outside. There are some services that can do that, but I never tried that.

**Comment by robin271** [comment]
That should do it. I will probably use a google cloud as my server. And I got one last question: Where did you all of your knowledge so that I can also understand how I all of it works. I tried looking up matching books but I couldn't really find any. Thank you in advance!

**Comment by JohannesDeml** [comment]
I would say most of my knowledge comes from University and just learning by doing. Sadly, I don't have a specific book I can point you to. I recommend doing small projects and setting small goals to get to where you want to get one step at a time.
